on:
  push:
    branches:
      - okk-short
   # todo on filechange or something for trigger
jobs:
  build-container:
    name: Build and push Rasa os
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub 
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_ACCES_TOKEN }}
    - name: Build and push to Docker Hub 
      uses: docker/build-push-action@v2 
      with: 
        context: ./Implementation/bot
        push: true 
        tags: tubskeller/rasa-experiment

